### ISSUE TITLE
Quotes not escaped in config

### ISSUE THREAD

**Issue by OrangeDog** [saltstack-formulas/logstash-formula#38]
This YAML incorrectly generates this config. Note the unescaped `"`s in the output.
```yaml
- plugin_name: ruby
  code: |-
    event.set("foo", "bar")
    return [event]
```
```
ruby {
    code => "event.set("foo", "bar")
    return [event]"
}
```
