### ISSUE TITLE
Multiple Message Lines?

### ISSUE THREAD

**Issue by bcheezum** [saltstack-formulas/logstash-formula#39]
Is it possible to add multiple message lines? I've tried multiple different configs but I've not been able to get anything to work.

Things I've tried:

```    filters:
        -
            plugin_name: grok
            match:
                message: '["pattern1","pattern2"]'
            add_field:
                received_at: '%{@timestamp}'
                received_from: '%{host}'
```

```    filters:
        -
            plugin_name: grok
            match:
                message: "pattern1"
                message: "pattern2"
            add_field:
                received_at: '%{@timestamp}'
                received_from: '%{host}'
```

And a bunch of other random things.

**Comment by myii** [comment]
@bcheezum I have no familiarity with this formula but how about trying a multi-line string like is used in this [`pillar.example`](https://github.com/saltstack-formulas/nginx-formula/blob/c539594b199dbdb8c586126373c0a6af676f23f5/pillar.example#L116-L119)?

**Comment by myii** [comment]
Note, the extra whitespace at the beginning of each line was simply for aesthetic purposes.  So a standard 2-space indent is what you should test.  I.e. something like:

```yaml
        -
            plugin_name: grok
            match:
                message: |-
                  pattern1
                  pattern2
```
